version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres-user:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  postgres-journal:
    image: postgres:15
    environment:
      POSTGRES_DB: journaldb
      POSTGRES_USER: journal
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  journal-service:
    build: ./journal-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - postgres-journal
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-journal:5432/journaldb
      SPRING_DATASOURCE_USERNAME: journal
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
