spring:
  application:
    name: journal-service
  datasource:
    url: jdbc:mysql://localhost:3306/journaldb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: journal-group
    auto-offset-reset: earliest
